/* tslint:disable */
/* eslint-disable */
/**
 * Dinero API
 * Welcome to our endpoint documentation. Please try to carefully read our general documentation found on <a href=\"https://developer.dinero.dk/\">developer.dinero.dk</a> for information regarding the authorization proces, status and errorcodes, FAQ, Postman tutorial etc. <br><br>Once authorized, you simply add \'Authorization: Bearer <access-token>\' to the header of your requests. On the page below, you\'ll find all our endpoints documented as well as possible, but if you have any questions regarding an endpoint, or an error in the description, please contact us on <a href=\"mailto:api@dinero.dk\">api@dinero.dk.</a> 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Model for sending an email for an invoice.
 * @export
 * @interface ApiMailoutModel
 */
export interface ApiMailoutModel {
    /**
     * Optional timestamp of version.  If given validate that you got the latest version.  This can be used to ensure that the voucher has not been changed since you last fetched it.  Defaults to latest version.
     * @type {string}
     * @memberof ApiMailoutModel
     */
    'timestamp'?: string | null;
    /**
     * Sender email. Defaults to organization email if left empty.
     * @type {string}
     * @memberof ApiMailoutModel
     */
    'sender'?: string | null;
    /**
     * Set to true, if copy should be send to sender. Defaults to false.
     * @type {boolean}
     * @memberof ApiMailoutModel
     */
    'ccToSender'?: boolean | null;
    /**
     * Receiver email. Defaults to contact email if left empty. If left empty, the contact needs to have an email, otherwise it will cause a bad request.  For multiple receivers a comma separated list is also allowed. Fx \'customer@dinero.dk,extrareceiver@dinero.dk\'
     * @type {string}
     * @memberof ApiMailoutModel
     */
    'receiver'?: string | null;
    /**
     * The subject of the email. Defaults to \'{Type} {Number}\' (according to the selected invoice language). Fx \'Invoice 3\', \'Credit note 4\' or \'Offer 12\'.
     * @type {string}
     * @memberof ApiMailoutModel
     */
    'subject'?: string | null;
    /**
     * Body of the email. If set, then it must contain the tag: [link-to-pdf], so that a link to the pdf can be included.  If left empty, defaults to template created in dinero.
     * @type {string}
     * @memberof ApiMailoutModel
     */
    'message'?: string | null;
    /**
     * Defaults to invoice settings (Fakturaindstillinger > Standard udsendelses-indstillinger). If true, the voucher will be attached to the email as pdf.
     * @type {boolean}
     * @memberof ApiMailoutModel
     */
    'addVoucherAsPdfAttachment'?: boolean | null;
    /**
     * Defaults to false. Determines if TrustPilotEmail should be added as BCC or not.
     * @type {boolean}
     * @memberof ApiMailoutModel
     */
    'shouldAddTrustPilotEmailAsBcc': boolean;
}

