/* tslint:disable */
/* eslint-disable */
/**
 * Dinero API
 * Welcome to our endpoint documentation. Please try to carefully read our general documentation found on <a href=\"https://developer.dinero.dk/\">developer.dinero.dk</a> for information regarding the authorization proces, status and errorcodes, FAQ, Postman tutorial etc. <br><br>Once authorized, you simply add \'Authorization: Bearer <access-token>\' to the header of your requests. On the page below, you\'ll find all our endpoints documented as well as possible, but if you have any questions regarding an endpoint, or an error in the description, please contact us on <a href=\"mailto:api@dinero.dk\">api@dinero.dk.</a> 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressPlacement } from './address-placement';
// May contain unused imports in some cases
// @ts-ignore
import type { InvoiceTheme } from './invoice-theme';
// May contain unused imports in some cases
// @ts-ignore
import type { LogoType } from './logo-type';

/**
 * Model for invoice templates
 * @export
 * @interface InvoiceTemplateModel
 */
export interface InvoiceTemplateModel {
    /**
     * Id of the template
     * @type {string}
     * @memberof InvoiceTemplateModel
     */
    'id': string;
    /**
     * The name to identify the template
     * @type {string}
     * @memberof InvoiceTemplateModel
     */
    'name'?: string | null;
    /**
     * Is true for the default template
     * @type {boolean}
     * @memberof InvoiceTemplateModel
     */
    'isDefault': boolean;
    /**
     * 
     * @type {InvoiceTheme}
     * @memberof InvoiceTemplateModel
     */
    'theme': InvoiceTheme;
    /**
     * Primary color used in theme
     * @type {string}
     * @memberof InvoiceTemplateModel
     */
    'primaryColor'?: string | null;
    /**
     * Secondary color used in theme
     * @type {string}
     * @memberof InvoiceTemplateModel
     */
    'secondaryColor'?: string | null;
    /**
     * 
     * @type {AddressPlacement}
     * @memberof InvoiceTemplateModel
     */
    'addressPlacement': AddressPlacement;
    /**
     * Font used for template
     * @type {string}
     * @memberof InvoiceTemplateModel
     */
    'font'?: string | null;
    /**
     * 
     * @type {LogoType}
     * @memberof InvoiceTemplateModel
     */
    'logoType': LogoType;
    /**
     * Logo text
     * @type {string}
     * @memberof InvoiceTemplateModel
     */
    'logoText'?: string | null;
    /**
     * File guid for logo
     * @type {string}
     * @memberof InvoiceTemplateModel
     */
    'logoFileGuid'?: string | null;
    /**
     * Max width for logo
     * @type {number}
     * @memberof InvoiceTemplateModel
     */
    'maxImageWidthMm': number;
    /**
     * Show company info on template
     * @type {boolean}
     * @memberof InvoiceTemplateModel
     */
    'showCompanyInfo': boolean;
    /**
     * Show payment conditions on template
     * @type {boolean}
     * @memberof InvoiceTemplateModel
     */
    'showPaymentConditions': boolean;
    /**
     * Show logo on template
     * @type {boolean}
     * @memberof InvoiceTemplateModel
     */
    'showLogo': boolean;
    /**
     * Show line quantity on template
     * @type {boolean}
     * @memberof InvoiceTemplateModel
     */
    'showLineQuantity': boolean;
    /**
     * Show line unit on template
     * @type {boolean}
     * @memberof InvoiceTemplateModel
     */
    'showLineUnit': boolean;
    /**
     * File guid for image. Can be used for background and header
     * @type {string}
     * @memberof InvoiceTemplateModel
     */
    'imageFileUploadGuid'?: string | null;
    /**
     * Text color on image
     * @type {string}
     * @memberof InvoiceTemplateModel
     */
    'imageTextColor'?: string | null;
}



