/* tslint:disable */
/* eslint-disable */
/**
 * Dinero API
 * Welcome to our endpoint documentation. Please try to carefully read our general documentation found on <a href=\"https://developer.dinero.dk/\">developer.dinero.dk</a> for information regarding the authorization proces, status and errorcodes, FAQ, Postman tutorial etc. <br><br>Once authorized, you simply add \'Authorization: Bearer <access-token>\' to the header of your requests. On the page below, you\'ll find all our endpoints documented as well as possible, but if you have any questions regarding an endpoint, or an error in the description, please contact us on <a href=\"mailto:api@dinero.dk\">api@dinero.dk.</a> 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Organization information
 * @export
 * @interface OrganizationReadModel
 */
export interface OrganizationReadModel {
    /**
     * Name of the organization
     * @type {string}
     * @memberof OrganizationReadModel
     */
    'name'?: string | null;
    /**
     * Id of the organization
     * @type {number}
     * @memberof OrganizationReadModel
     */
    'id'?: number | null;
    /**
     * Whether the organization is VIP or default
     * @type {string}
     * @memberof OrganizationReadModel
     */
    'type'?: string | null;
    /**
     * Whether the organization has Dinero Pro access
     * @type {boolean}
     * @memberof OrganizationReadModel
     */
    'isPro'?: boolean | null;
    /**
     * Whether the organization has a paid Dinero Pro subscription
     * @type {boolean}
     * @memberof OrganizationReadModel
     */
    'isPayingPro'?: boolean | null;
    /**
     * If an organization does not use VAT
     * @type {boolean}
     * @memberof OrganizationReadModel
     */
    'isVatFree': boolean;
    /**
     * Email of the organization
     * @type {string}
     * @memberof OrganizationReadModel
     */
    'email'?: string | null;
    /**
     * Organization phone number
     * @type {string}
     * @memberof OrganizationReadModel
     */
    'phone'?: string | null;
    /**
     * Organization street
     * @type {string}
     * @memberof OrganizationReadModel
     */
    'street'?: string | null;
    /**
     * Organization city
     * @type {string}
     * @memberof OrganizationReadModel
     */
    'city'?: string | null;
    /**
     * Organization zip code
     * @type {string}
     * @memberof OrganizationReadModel
     */
    'zipCode'?: string | null;
    /**
     * Att. person of the organization
     * @type {string}
     * @memberof OrganizationReadModel
     */
    'attPerson'?: string | null;
    /**
     * Whether the organization is a tax free union
     * @type {boolean}
     * @memberof OrganizationReadModel
     */
    'isTaxFreeUnion': boolean;
    /**
     * Vat number for organization
     * @type {string}
     * @memberof OrganizationReadModel
     */
    'vatNumber'?: string | null;
    /**
     * Organization country code
     * @type {string}
     * @memberof OrganizationReadModel
     */
    'countryKey'?: string | null;
    /**
     * Website for organization
     * @type {string}
     * @memberof OrganizationReadModel
     */
    'website'?: string | null;
}

