/* tslint:disable */
/* eslint-disable */
/**
 * Dinero API
 * Welcome to our endpoint documentation. Please try to carefully read our general documentation found on <a href=\"https://developer.dinero.dk/\">developer.dinero.dk</a> for information regarding the authorization proces, status and errorcodes, FAQ, Postman tutorial etc. <br><br>Once authorized, you simply add \'Authorization: Bearer <access-token>\' to the header of your requests. On the page below, you\'ll find all our endpoints documented as well as possible, but if you have any questions regarding an endpoint, or an error in the description, please contact us on <a href=\"mailto:api@dinero.dk\">api@dinero.dk.</a> 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompanyTypeCodeViewModel } from './company-type-code-view-model';
// May contain unused imports in some cases
// @ts-ignore
import type { DateRangeViewModel } from './date-range-view-model';

/**
 * 
 * @export
 * @interface OrganizationCreateModel
 */
export interface OrganizationCreateModel {
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'zipCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'email'?: string | null;
    /**
     * 
     * @type {CompanyTypeCodeViewModel}
     * @memberof OrganizationCreateModel
     */
    'companyType': CompanyTypeCodeViewModel;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'countryCode'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrganizationCreateModel
     */
    'cvrNumber'?: number | null;
    /**
     * 
     * @type {DateRangeViewModel}
     * @memberof OrganizationCreateModel
     */
    'firstAccountingYear': DateRangeViewModel;
    /**
     * 
     * @type {DateRangeViewModel}
     * @memberof OrganizationCreateModel
     */
    'currentAccountingYear': DateRangeViewModel;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationCreateModel
     */
    'isVatFree'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationCreateModel
     */
    'isTaxFreeUnion'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'attName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'streetName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'houseNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'floor'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreateModel
     */
    'door'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationCreateModel
     */
    'hasAcceptedDataProcessingAgreement': boolean;
}

