/* tslint:disable */
/* eslint-disable */
/**
 * Dinero API
 * Welcome to our endpoint documentation. Please try to carefully read our general documentation found on <a href=\"https://developer.dinero.dk/\">developer.dinero.dk</a> for information regarding the authorization proces, status and errorcodes, FAQ, Postman tutorial etc. <br><br>Once authorized, you simply add \'Authorization: Bearer <access-token>\' to the header of your requests. On the page below, you\'ll find all our endpoints documented as well as possible, but if you have any questions regarding an endpoint, or an error in the description, please contact us on <a href=\"mailto:api@dinero.dk\">api@dinero.dk.</a> 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Product information
 * @export
 * @interface ProductCreateModel
 */
export interface ProductCreateModel {
    /**
     * Number of the product (Varekode)
     * @type {string}
     * @memberof ProductCreateModel
     */
    'productNumber'?: string | null;
    /**
     * Product name
     * @type {string}
     * @memberof ProductCreateModel
     */
    'name'?: string | null;
    /**
     * Amount excl. VAT
     * @type {number}
     * @memberof ProductCreateModel
     */
    'baseAmountValue': number;
    /**
     * Quantity
     * @type {number}
     * @memberof ProductCreateModel
     */
    'quantity': number;
    /**
     * Account number
     * @type {number}
     * @memberof ProductCreateModel
     */
    'accountNumber': number;
    /**
     * Product unit. Available unit types: hours, parts, km, day, week, month, kilogram, cubicMetre, set, litre, box, case, carton, metre, package, shipment, squareMetre, session, tonne.
     * @type {string}
     * @memberof ProductCreateModel
     */
    'unit': string;
    /**
     * Your external id  This can be used for ID\'ing in external apps/services e.g. a web shop.  The maximum length is 128 characters
     * @type {string}
     * @memberof ProductCreateModel
     */
    'externalReference'?: string | null;
    /**
     * Comment for the product.   The comment will be shown on invoices with the product by default.
     * @type {string}
     * @memberof ProductCreateModel
     */
    'comment'?: string | null;
}

