/* tslint:disable */
/* eslint-disable */
/**
 * Dinero API
 * Welcome to our endpoint documentation. Please try to carefully read our general documentation found on <a href=\"https://developer.dinero.dk/\">developer.dinero.dk</a> for information regarding the authorization proces, status and errorcodes, FAQ, Postman tutorial etc. <br><br>Once authorized, you simply add \'Authorization: Bearer <access-token>\' to the header of your requests. On the page below, you\'ll find all our endpoints documented as well as possible, but if you have any questions regarding an endpoint, or an error in the description, please contact us on <a href=\"mailto:api@dinero.dk\">api@dinero.dk.</a> 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PurchaseVoucherLineReadModel } from './purchase-voucher-line-read-model';
// May contain unused imports in some cases
// @ts-ignore
import type { PurchaseVoucherTotalReadModel } from './purchase-voucher-total-read-model';

/**
 * 
 * @export
 * @interface PurchaseCreditNoteReadModel
 */
export interface PurchaseCreditNoteReadModel {
    /**
     * Guid of the credit note
     * @type {string}
     * @memberof PurchaseCreditNoteReadModel
     */
    'guid': string;
    /**
     * Id of the invoice the credit note is based on.
     * @type {string}
     * @memberof PurchaseCreditNoteReadModel
     */
    'creditNoteFor'?: string | null;
    /**
     * Id of the file associated with the purchase credit note.
     * @type {string}
     * @memberof PurchaseCreditNoteReadModel
     */
    'fileGuid'?: string | null;
    /**
     * Number of the purchase credit note
     * @type {number}
     * @memberof PurchaseCreditNoteReadModel
     */
    'creditNoteNumber'?: number | null;
    /**
     * Guid of the contact associated with the credit note
     * @type {string}
     * @memberof PurchaseCreditNoteReadModel
     */
    'contactGuid'?: string | null;
    /**
     * Date of the credit note
     * @type {string}
     * @memberof PurchaseCreditNoteReadModel
     */
    'date'?: string | null;
    /**
     * The currency used on the credit note. Defaults to DKK if null.
     * @type {string}
     * @memberof PurchaseCreditNoteReadModel
     */
    'currency'?: string | null;
    /**
     * The list of lines associated with the credit note
     * @type {Array<PurchaseVoucherLineReadModel>}
     * @memberof PurchaseCreditNoteReadModel
     */
    'lines'?: Array<PurchaseVoucherLineReadModel> | null;
    /**
     * Timestamp used for verifying version when updating or changing the credit note
     * @type {string}
     * @memberof PurchaseCreditNoteReadModel
     */
    'timestamp'?: string | null;
    /**
     * The status of a purchase credit note can be: Draft, Paid, Editing, Booked, Overdue, or Overpaid
     * @type {string}
     * @memberof PurchaseCreditNoteReadModel
     */
    'status'?: string | null;
    /**
     * Where the credit note was booked from in the system.  the available types are Ukendt, Web, Assistent, Mobil-app, Pensopay, System, Kassekladde, Kontingentopkrævning, Abonnement and API (with client id)
     * @type {string}
     * @memberof PurchaseCreditNoteReadModel
     */
    'bookedByType'?: string | null;
    /**
     * The username of the user that booked the credit note
     * @type {string}
     * @memberof PurchaseCreditNoteReadModel
     */
    'bookedByUsername'?: string | null;
    /**
     * The date for when the credit note is booked
     * @type {string}
     * @memberof PurchaseCreditNoteReadModel
     */
    'bookingTime'?: string | null;
    /**
     * The total sums of the purchase voucher credit note
     * @type {Array<PurchaseVoucherTotalReadModel>}
     * @memberof PurchaseCreditNoteReadModel
     */
    'totals'?: Array<PurchaseVoucherTotalReadModel> | null;
}

