/* tslint:disable */
/* eslint-disable */
/**
 * Dinero API
 * Welcome to our endpoint documentation. Please try to carefully read our general documentation found on <a href=\"https://developer.dinero.dk/\">developer.dinero.dk</a> for information regarding the authorization proces, status and errorcodes, FAQ, Postman tutorial etc. <br><br>Once authorized, you simply add \'Authorization: Bearer <access-token>\' to the header of your requests. On the page below, you\'ll find all our endpoints documented as well as possible, but if you have any questions regarding an endpoint, or an error in the description, please contact us on <a href=\"mailto:api@dinero.dk\">api@dinero.dk.</a> 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The total sum of a voucher
 * @export
 * @interface PurchaseVoucherTotalReadModel
 */
export interface PurchaseVoucherTotalReadModel {
    /**
     * Label of the total
     * @type {string}
     * @memberof PurchaseVoucherTotalReadModel
     */
    'label'?: string | null;
    /**
     * The amount of money in DKK
     * @type {number}
     * @memberof PurchaseVoucherTotalReadModel
     */
    'total': number;
    /**
     * The type of total, can be SubTotal, Vat, or Total
     * @type {string}
     * @memberof PurchaseVoucherTotalReadModel
     */
    'type'?: string | null;
    /**
     * Position of the line, used for showing in UI
     * @type {number}
     * @memberof PurchaseVoucherTotalReadModel
     */
    'position': number;
}

