/* tslint:disable */
/* eslint-disable */
/**
 * Dinero API
 * Welcome to our endpoint documentation. Please try to carefully read our general documentation found on <a href=\"https://developer.dinero.dk/\">developer.dinero.dk</a> for information regarding the authorization proces, status and errorcodes, FAQ, Postman tutorial etc. <br><br>Once authorized, you simply add \'Authorization: Bearer <access-token>\' to the header of your requests. On the page below, you\'ll find all our endpoints documented as well as possible, but if you have any questions regarding an endpoint, or an error in the description, please contact us on <a href=\"mailto:api@dinero.dk\">api@dinero.dk.</a> 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PurchaseVoucherLineReadModel } from './purchase-voucher-line-read-model';
// May contain unused imports in some cases
// @ts-ignore
import type { PurchaseVoucherTotalReadModel } from './purchase-voucher-total-read-model';

/**
 * Model returned by the api when fetching purchasevouchers
 * @export
 * @interface PurchaseVoucherFetchReadModel
 */
export interface PurchaseVoucherFetchReadModel {
    /**
     * The status of a cash purchase voucher, can be: Draft, Paid, or Editing. The status of a credit purchase voucher can be: Draft, Paid, Editing, Booked, Overdue, or Overpaid
     * @type {string}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'status'?: string | null;
    /**
     * Guid of the file associated with the voucher, optional value
     * @type {string}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'fileGuid'?: string | null;
    /**
     * Number of the voucher
     * @type {number}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'voucherNumber'?: number | null;
    /**
     * Date of the purchase
     * @type {string}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'voucherDate'?: string | null;
    /**
     * Date of the payment of the voucher, is the same as voucherdate if the purchase is cash
     * @type {string}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'paymentDate'?: string | null;
    /**
     * The region the purchase is made from, only used on cash purchases, can be: DK, EU, or World
     * @type {string}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'regionKey'?: string | null;
    /**
     * Type of purchase, can be cash or credit
     * @type {string}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'purchaseType'?: string | null;
    /**
     * The list of lines associated with the purchase
     * @type {Array<PurchaseVoucherLineReadModel>}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'lines'?: Array<PurchaseVoucherLineReadModel> | null;
    /**
     * Account number of the deposit to book on, only used for cash purchases
     * @type {number}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'depositAccountNumber'?: number | null;
    /**
     * Guid of the contact associated with the purchase, can only have a value on credit purchases
     * @type {string}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'contactGuid'?: string | null;
    /**
     * Your external id  This can be used for ID\'ing in external apps/services e.g. a web shop.  The maximum length is 128 characters
     * @type {string}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'externalReference'?: string | null;
    /**
     * The total sums of the purchase voucher
     * @type {Array<PurchaseVoucherTotalReadModel>}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'voucherTotals'?: Array<PurchaseVoucherTotalReadModel> | null;
    /**
     * Indicates whether the purchase possibly should be a fixed asset, instead of a purchase.
     * @type {boolean}
     * @memberof PurchaseVoucherFetchReadModel
     */
    'shouldPossiblyBeFixedAsset': boolean;
}

