/* tslint:disable */
/* eslint-disable */
/**
 * Dinero API
 * Welcome to our endpoint documentation. Please try to carefully read our general documentation found on <a href=\"https://developer.dinero.dk/\">developer.dinero.dk</a> for information regarding the authorization proces, status and errorcodes, FAQ, Postman tutorial etc. <br><br>Once authorized, you simply add \'Authorization: Bearer <access-token>\' to the header of your requests. On the page below, you\'ll find all our endpoints documented as well as possible, but if you have any questions regarding an endpoint, or an error in the description, please contact us on <a href=\"mailto:api@dinero.dk\">api@dinero.dk.</a> 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReminderViewModel
 */
export interface ReminderViewModel {
    /**
     * Timestamp to validate against. This is a safety measure to ensure that an API partner is only making changes to the latest version of the entity.  The timestamp is generated on Dinero\'s server every time the entity is updated, and is returned as a part of CreatedResponse and UpdatedResponse. It\'s also available on the entity itself.  If you get a timestamp outdated exception (error code 58), you will need to get the latest version of the entity and use its timestamp.
     * @type {string}
     * @memberof ReminderViewModel
     */
    'timestamp': string;
    /**
     * Reminder date
     * @type {string}
     * @memberof ReminderViewModel
     */
    'date': string;
    /**
     * Reminder title
     * @type {string}
     * @memberof ReminderViewModel
     */
    'title'?: string | null;
    /**
     * Reminder description
     * @type {string}
     * @memberof ReminderViewModel
     */
    'description'?: string | null;
    /**
     * Should the reminder include debt collection warning text
     * @type {boolean}
     * @memberof ReminderViewModel
     */
    'withDebtCollectionWarning': boolean;
    /**
     * Should the reminder include fee
     * @type {boolean}
     * @memberof ReminderViewModel
     */
    'withFee': boolean;
    /**
     * Should the reminder include interest fee
     * @type {boolean}
     * @memberof ReminderViewModel
     */
    'withInterestFee': boolean;
    /**
     * Should the reminder include compensation fee
     * @type {boolean}
     * @memberof ReminderViewModel
     */
    'withCompensationFee': boolean;
    /**
     * 
     * @type {number}
     * @memberof ReminderViewModel
     */
    'id'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ReminderViewModel
     */
    'isDraft': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReminderViewModel
     */
    'isDeleted': boolean;
    /**
     * Reminder number
     * @type {number}
     * @memberof ReminderViewModel
     */
    'number': number;
    /**
     * The text to show if \"WithDebtCollectionWarning\" is selected
     * @type {string}
     * @memberof ReminderViewModel
     */
    'debtCollectionNoticeText'?: string | null;
    /**
     * The text to show with InvoiceTotalInclVatAmount
     * @type {string}
     * @memberof ReminderViewModel
     */
    'invoiceTotalInclVatAmountText'?: string | null;
    /**
     * The invoice total amount incl vat
     * @type {number}
     * @memberof ReminderViewModel
     */
    'invoiceTotalInclVatAmount': number;
    /**
     * The text to show with FeeAmount
     * @type {string}
     * @memberof ReminderViewModel
     */
    'feeAmountText'?: string | null;
    /**
     * The fee
     * @type {number}
     * @memberof ReminderViewModel
     */
    'feeAmount': number;
    /**
     * The text to show with InterestAmount
     * @type {string}
     * @memberof ReminderViewModel
     */
    'interestAmountText'?: string | null;
    /**
     * The interest
     * @type {number}
     * @memberof ReminderViewModel
     */
    'interestAmount'?: number | null;
    /**
     * Indicates if the reminder can have a compensation fee
     * @type {boolean}
     * @memberof ReminderViewModel
     */
    'compensationFeeAvailable': boolean;
    /**
     * The text to show with CompensationFeeAmount
     * @type {string}
     * @memberof ReminderViewModel
     */
    'compensationFeeAmountText'?: string | null;
    /**
     * The compensation fee
     * @type {number}
     * @memberof ReminderViewModel
     */
    'compensationFeeAmount': number;
    /**
     * The text to show with AccumulatedFeesAndInterestAmount
     * @type {string}
     * @memberof ReminderViewModel
     */
    'accumulatedFeesAndInterestAmountText'?: string | null;
    /**
     * Reminder fees, interest rates and any compensation fee from previous reminders
     * @type {number}
     * @memberof ReminderViewModel
     */
    'accumulatedFeesAndInterestAmount': number;
    /**
     * The text to show with PaidAmount
     * @type {string}
     * @memberof ReminderViewModel
     */
    'paidAmountText'?: string | null;
    /**
     * Already paid amount
     * @type {number}
     * @memberof ReminderViewModel
     */
    'paidAmount': number;
    /**
     * Text for ReminderTotalInclVatAmount
     * @type {string}
     * @memberof ReminderViewModel
     */
    'reminderTotalInclVatAmountText'?: string | null;
    /**
     * Total amount for the reminder
     * @type {number}
     * @memberof ReminderViewModel
     */
    'reminderTotalInclVatAmount': number;
}

