/* tslint:disable */
/* eslint-disable */
/**
 * Dinero API
 * Welcome to our endpoint documentation. Please try to carefully read our general documentation found on <a href=\"https://developer.dinero.dk/\">developer.dinero.dk</a> for information regarding the authorization proces, status and errorcodes, FAQ, Postman tutorial etc. <br><br>Once authorized, you simply add \'Authorization: Bearer <access-token>\' to the header of your requests. On the page below, you\'ll find all our endpoints documented as well as possible, but if you have any questions regarding an endpoint, or an error in the description, please contact us on <a href=\"mailto:api@dinero.dk\">api@dinero.dk.</a> 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Default SalesVoucherSettings
 * @export
 * @interface SalesVoucherSetttingsModel
 */
export interface SalesVoucherSetttingsModel {
    /**
     * The users preference, whether the lines should be displayed incl VAT or not
     * @type {boolean}
     * @memberof SalesVoucherSetttingsModel
     */
    'linesInclVat': boolean;
    /**
     * FI71 paymentidentification. For the FIK code +71<000000016460909+12345678< this would be 12345678
     * @type {string}
     * @memberof SalesVoucherSetttingsModel
     */
    'fikCode'?: string | null;
    /**
     * The users preference, whether to use FIK code or not
     * @type {boolean}
     * @memberof SalesVoucherSetttingsModel
     */
    'useFikCode': boolean;
    /**
     * Default voucher line account
     * @type {number}
     * @memberof SalesVoucherSetttingsModel
     */
    'defaultAccountNumber': number;
    /**
     * The default template id to use for design.
     * @type {string}
     * @memberof SalesVoucherSetttingsModel
     */
    'invoiceTemplateId'?: string | null;
    /**
     * The users preference, whether to attach voucher as pdf on e-mails
     * @type {boolean}
     * @memberof SalesVoucherSetttingsModel
     */
    'addVoucherAsPdfAttachment': boolean;
    /**
     * The default reminder fee to use on any reminders created from the voucher
     * @type {number}
     * @memberof SalesVoucherSetttingsModel
     */
    'reminderFee': number;
    /**
     * The default reminder interest rate to use on any reminders created from the voucher
     * @type {number}
     * @memberof SalesVoucherSetttingsModel
     */
    'reminderInterestRate': number;
    /**
     * The Trustpilot-email to include as BCC in invoice mail outs.
     * @type {string}
     * @memberof SalesVoucherSetttingsModel
     */
    'trustPilotEmail'?: string | null;
    /**
     * The default payment condition number of days
     * @type {number}
     * @memberof SalesVoucherSetttingsModel
     */
    'paymentConditionNumberOfDays': number;
    /**
     * The default payment condition type
     * @type {string}
     * @memberof SalesVoucherSetttingsModel
     */
    'paymentConditionType'?: string | null;
}

