/* tslint:disable */
/* eslint-disable */
/**
 * Dinero API
 * Welcome to our endpoint documentation. Please try to carefully read our general documentation found on <a href=\"https://developer.dinero.dk/\">developer.dinero.dk</a> for information regarding the authorization proces, status and errorcodes, FAQ, Postman tutorial etc. <br><br>Once authorized, you simply add \'Authorization: Bearer <access-token>\' to the header of your requests. On the page below, you\'ll find all our endpoints documented as well as possible, but if you have any questions regarding an endpoint, or an error in the description, please contact us on <a href=\"mailto:api@dinero.dk\">api@dinero.dk.</a> 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VoucherMailoutReadModel
 */
export interface VoucherMailoutReadModel {
    /**
     * Mailout id
     * @type {number}
     * @memberof VoucherMailoutReadModel
     */
    'id': number;
    /**
     * Sent date
     * @type {string}
     * @memberof VoucherMailoutReadModel
     */
    'date': string;
    /**
     * First time the mailout was seen
     * @type {string}
     * @memberof VoucherMailoutReadModel
     */
    'seenAt'?: string | null;
    /**
     * Email of the sender
     * @type {string}
     * @memberof VoucherMailoutReadModel
     */
    'sender'?: string | null;
    /**
     * Email(s) of the receiver
     * @type {string}
     * @memberof VoucherMailoutReadModel
     */
    'receiver'?: string | null;
    /**
     * Mailout subject
     * @type {string}
     * @memberof VoucherMailoutReadModel
     */
    'subject'?: string | null;
    /**
     * Mailout message
     * @type {string}
     * @memberof VoucherMailoutReadModel
     */
    'message'?: string | null;
    /**
     * Number of times the mailout was downloaded
     * @type {number}
     * @memberof VoucherMailoutReadModel
     */
    'downloadCount': number;
    /**
     * Number of times the mailout was printed
     * @type {number}
     * @memberof VoucherMailoutReadModel
     */
    'printCount': number;
    /**
     * Possible values are None, Einvoice, ElectronicInvoiceReminder, TradeOffer, OrderConfirmation, Mailout, Inkasso, PreReminder, ManualMailout, ManualTradeOfferMailout and Reminder
     * @type {string}
     * @memberof VoucherMailoutReadModel
     */
    'type'?: string | null;
    /**
     * Possible values are Pending, Sent, SeenByCustomer, Failed, and ManuallySent
     * @type {string}
     * @memberof VoucherMailoutReadModel
     */
    'status'?: string | null;
    /**
     * Possible values for type TradeOffer, OrderConfirmation, Mailout, Inkasso, PreReminder and Reminder are Download, Print, WebView, SoftBounce, HardBounce, Rejected, Spam, Sent, Invalid, Queued, Scheduled and Failed                Possible values for type Einvoice, ElectronicInvoiceReminder are SentToDispatching, SentToProvider, SentToCustomer, InvalidDocument, IncompleteDocument, UnknownError, EndpointNotFound, AlreadyDispatched and TemporaryError
     * @type {string}
     * @memberof VoucherMailoutReadModel
     */
    'latestEvent'?: string | null;
    /**
     * Indicates if this object is an sms
     * @type {boolean}
     * @memberof VoucherMailoutReadModel
     */
    'isSmsMessage': boolean;
    /**
     * Indicates if copy of email is sent to sender
     * @type {boolean}
     * @memberof VoucherMailoutReadModel
     */
    'ccToSender': boolean;
}

